export { selectRoleEndpoint } from "./onboarding";
export { uploadDocumentEndpoint } from "./uploadDocument";
export { getUserProfileEndpoint } from "./getUserProfile";
export { getUserEndpoint } from "./getUser";
export { getVerificationDocsEndpoint } from "./getVerificationDocs";
export { verifyAllDocumentsEndpoint } from "./verifyAllDocuments";
export { getAllUsersEndpoint } from "./getAllUsers";
export { deleteUserEndpoint } from "./deleteUser";
export { checkVerificationEndpoint } from "./checkVerification";
